#!/usr/bin/bash
# ------------------------------------------------------------------------------
CEN_LEGAL="Copyright Dr. J. Pfennig (c) 2018-2025; "$"BSD License"
CEN_TITLE=$"Wait for Display and start X-Server"

PATH+="${0%/*}" . _centauri_bash_lib -a -d -f -m svc -o -r -t - '0.31:4' || exit 2

# Options
CEN_OPT_CONSOLE=            # see --console
CEN_OPT_DPI=                # see --dpi
CEN_OPT_INPUT=              # see --input
CEN_OPT_LIST=               # see --list
CEN_OPT_MODE=               # see --mode
CEN_OPT_NOWAIT=             # see --nowait
CEN_OPT_RUN=                # see --scale
CEN_OPT_SCALE=              # see --scale
CEN_OPT_SERVER=             # see --server
CEN_OPT_USER=               # see --user
CEN_OPT_XRES=               # see --xresources

# Data
CEN_RUN_MIN_ARGS=0          # min arg count, see arguments()
CEN_RUN_MAX_ARGS=0          # max arg count

DAT_GUI='xinit'             # default gui server/compositor

DAT_OCON=                   # original console
DAT_HRES=                   # screen horizontal resolution, see set_hres()
DAT_CARD=                   # path in /sys/class/drm/...
DAT_TEMP=                   # prefix for temporary files
DAT_ZOOM=                   # for QT_SCALE_FACTOR

                            # console setup ...
DAT_CONSOLE="${CEN_PATHS[6]}/console-setup"
                            # display manager configs...
DAT_LIGHTDM="${CEN_PATHS[2]}/lightdm/lightdm.conf"
DAT_LIGHTDG="${CEN_PATHS[2]}/lightdm/lightdm-gtk-greeter.conf"
DAT_DISPLAY="${CEN_PATHS[2]}/$CEN_NAME"
DAT_SDDM="${CEN_PATHS[2]}/sddm.conf"
                            # generated, used by --xresources
DAT_XRES="${CEN_PATHS[2]}/X11/Xresources/$CEN_NAME"
                            # used to save status
DAT_PERS="$CEN_ROOT/persistent/$CEN_NAME"
DAT_PERS_CONT=              # last status

# data from config file ...
DAT_CFG_CONSOLE=
DAT_CFG_LIGHTDM=
DAT_CFG_LIGHTDG=
DAT_CFG_DISPLAY=
DAT_CFG_SDDM=
DAT_CFG_XRES=

### configuration data gets overridden by /etc/default/centauridisplay ###

# dpi table, see set_mode and set_mode: <<name> <min-x-res> <dpi>>...
DAT_DPI_INFO=('pc 0 96'  'sd 1300 104'  'hd 1900 141'   '4k 2600 172'  '5k 2800 196')

# map colsolefonts to dpi
DAT_DPI_CONS=('190 18x32' '170 14x28' '150 12x24' '130 10x20' '100 10x18' '0 8x14')

# status data, see status_file() and DAT_PERS

CEN_DISPLAY_DPI0=               # main display dpi
CEN_DISPLAY_KEYB=               # 1 if detected
CEN_DISPLAY_MICE=               # number of mice (0 := empty)
CEN_DISPLAY_TNAM=               # name of detected touch display
CEN_DISPLAY_RDSI=               # Raspi-DSI rotation 0|180
CEN_DISPLAY_SCAL=               # scaling mode, 0 for manual

#context -v 2                   # debug output

# ------------------------------------------------------------------------------
# read or update status file: [-r|-u|-w]
# ------------------------------------------------------------------------------
status_file() {
    local stat=0 cont="$DAT_PERS_CONT"
    if [ "$1" = '-r' -o "$1" = '-u' ] ; then
        CEN_DISPLAY_DPI0='-'
        CEN_DISPLAY_KEYB='-'
        CEN_DISPLAY_MICE='-'
        CEN_DISPLAY_TNAM='-'
        CEN_DISPLAY_RDSI='-'
        CEN_DISPLAY_SCAL='-'
        if [ -e "$DAT_PERS" ] ; then
            if embed -b "$DAT_PERS" ; then
                trace -a -c ' ' "Loaded:" "$DAT_PERS"
            else
                stat=1
            fi
        fi
    fi

    if [ "$1" = '-u' ] ; then
        # video=DSI-1:800x480@60,rotate=180
        local wrds word
        readline -a wrds -i '/proc/cmdline' -x -w
        if listsearch -g -m word -i wrds -- 'video=DSI-*' ; then
            word="${word#*rotate=}"
            [ -n "${word//[0-9]/}" ] && CEN_DISPLAY_RDSI=0 || CEN_DISPLAY_RDSI="$word"
            trace -a -c ' ' "DSI rotation :" "$CEN_DISPLAY_RDSI"
        else
            CEN_DISPLAY_RDSI='-'
        fi
    fi

    DAT_PERS_CONT="$CEN_DISPLAY_DPI0 $CEN_DISPLAY_KEYB $CEN_DISPLAY_MICE"
    DAT_PERS_CONT+=" $CEN_DISPLAY_TNAM $CEN_DISPLAY_RDSI $CEN_DISPLAY_SCAL"

    if [ "$1" = '-w' ] ; then
        if [ "$cont" = "$DAT_PERS_CONT" ] ; then
            trace -a -c ' ' "No status change" ; return 0
        fi
        serialize -n "$DAT_PERS" -m 664 -w -- CEN_DISPLAY_DPI0 CEN_DISPLAY_KEYB \
            CEN_DISPLAY_MICE CEN_DISPLAY_TNAM CEN_DISPLAY_RDSI CEN_DISPLAY_SCAL || stat=1
    fi

    return "$stat"
}

# ------------------------------------------------------------------------------
# don't switch away for issue screen
# ------------------------------------------------------------------------------
# The centauriissue service will display something on console #8. This function
# stops plymouth-quit-wait to prevent a wait dependency loop and also defers the
# start of a display manager, which would switch away from console #8.
# ------------------------------------------------------------------------------
has_issue() {
    [ -d "$CEN_ROOT/persistent/issue.d" ] || return 0
    message -a $"Waiting for 'centauriissue' service"
    runservice -v stop 'plymouth-quit-wait'
    local maxw=30
    while [ "$maxw" -gt 0 ] ; do
        ((maxw -= 1)) ; timer -w 2
        [ -d "$CEN_ROOT/persistent/issue.d" ] || return 0
    done
    message -a $"Wait timeout, starting display manager"
    return 1
}

# ------------------------------------------------------------------------------
# Check for display (wait if CEN_OPT_NOWAIT is empty)
# ------------------------------------------------------------------------------
has_display() {
    # wait for intel-pc display
    ___wait_pc() {
        local card xcon
        for card in /sys/class/drm/card* ; do
            [ -r "$card/status" ] || continue
            [ "${card/LVDS/}" != "$card" ] && continue   # pokini/notebook
            read xcon <"$card/status"
            [ "$xcon" = 'connected' ] || continue
            DAT_CARD="$card"
            trace -a -c $"Display connected" "$card"
            return 0
        done
        return 1
    }

    # wait for raspi display (legacy)
    ___wait_raspi() {
       trace -a $"Rasberry Pi using LCD display, assume connected"
       DAT_CARD='raspi-lcd'
       return 0
    }

    # wait for unknown
    ___wait_unknown() {
        if [ -e '/sys/class/drm/version' ] ; then
            error $"Found no DRM card, no display connected"
            return 1
        fi
        warning $"Cannot check for display, assume connected"
        return 0
    }

    # wait for display to be connected
    local card
    ___wait_loop() {
        local xcon wtim="$1" wmax="$2" wrun wras
        # raspberry might have a DSI display
        if system -c raspi-config ; then
            set -- /sys/class/backlight/*
            [ -e "$1" ] && wras=1
        fi
        if [ -n "$wras" ] ; then
            wrun=___wait_raspi
        # external display ...
        else
            set -- /sys/class/drm/card*
            if [ -e "$1" ] ; then
                wrun=___wait_pc
            # unknown
            else
                wrun=___wait_unknown
            fi
        fi
        while [ "${wmax:-1}" -ge 1 ] ; do
            $wrun && return 0                   # check for display
            [ -n "$DAT_CARD" ] || return 1      # no display
            if [ -n "$CEN_OPT_NOWAIT" ] ; then
                trace -a $"Display not connected" ; return 1
            fi
            if [ -n "$wmax" ] ; then
                ((wmax -= 1))
                message -a -p $"Display not connected, waiting %s" "$wtim [s]"
            fi
            timer -w "$wtim"
        done
        return 1
    }

    # --- main ---

    ___wait_loop 1 14 && return 0
    [ -n "$DAT_CARD" ] || return 4          # no display
    ___wait_loop 2  8 && return 0
    [ -n "$CEN_OPT_NOWAIT" ] && return 5
    message -a $"Display not connected, waiting..."
    ___wait_loop 5 && return 0 || return 5
}

# ------------------------------------------------------------------------------
# check for touch-display and keyboard
# ------------------------------------------------------------------------------
has_input() {
    local line name nkey nmou mcnt=0 ifil='/proc/bus/input/devices'
    [ -r "$ifil" ] || fatal $"Cannot read kernel info:" "$ifil"
    while read -r line ; do
        case "$line" in
        N:*)        name="${line#*=\"}" ; name="${name%\"}" ;;
        H:*sysrq*)  nkey="$name" ;;
        H:*mouse*)  nmou="$name" ; ((mcnt += 1)) ;;
        esac
    done < "$ifil"

    # simple logic no keyboard -> single mouse is touch
    if [ "$mcnt" -gt 1 ] ; then
        trace $"unknown status, multiple mice"
    elif [ -n "$nkey" ] ; then
        trace -c $"keyboard" "$nkey"
        trace -a -c $"mouse" "$nmou"
    elif [ "$mcnt" = 1 ] ; then
        trace -c $"touchscreen" "$nmou"
    else #if [ -z "$nmou" ] ; then
        trace $"no known hid input device"
    #else
    #    trace $"unknown status, multiple mice"
    fi

    status_file -u
    CEN_DISPLAY_KEYB="$nkey"
    CEN_DISPLAY_MICE="$mcnt"
    CEN_DISPLAY_TNAM="$nmou"
    status_file -w
}

# ------------------------------------------------------------------------------
# check if user runs Xorg or is logged on locally: [<user>|- [<console>]]
#
# Argument:     a user name to set 'usr_status_'  -or-  '-' to print a list
#               optionally followed by a console number.
#
# Returns (in 'usr_status_'):
#               <empty>    error or user not found
#               (:N)       running Xorg, console unknown, N is DISPLAY
#               vtN        running Xorg, console is N
#               ttyN       has a TTY login, no Xorg, console is N
#               (I)        has remote login, I is the ip-address
#
#               If a console number other than 0 is given and the console is in
#               use, the function returns status 2.
#
# Using 'who -s' to find user. Example output:
#
# local    tty1         2019-12-14 17:09                # console login
# local    tty7         2019-12-14 16:40 (:0)           # xorg ...
# local    pts/0        2019-12-14 16:40 (:0)
# local    pts/1        2019-12-14 16:40 (:0)
# local    pts/2        2019-12-14 16:41 (:0)
# jpf      pts/3        2019-12-14 16:42 (:1)           # xorg ...
# jpf      pts/4        2019-12-14 16:42 (:1)
# local    pts/5        2019-12-14 17:08 (10.21.2.25)   # ssh login
# ------------------------------------------------------------------------------
usr_status_=
usr_status() {
    local cusr="$1" ; [ "$cusr" = '-' ] && cusr=
    local cons="${2:-0}" cbsy
    system -c -f pgrep who
    usr_status_=

    # get console for Xorg display ids -> smap (data from prep)
    local svra svri sdis scon
    local -A smap
    # pgrep can return status 1 if nothing is found
    system -a svra -p -r -- pgrep -lax 'Xorg'
    for svri in "${svra[@]}" ; do
        set -f ; set -- $svri ; set +f
        shift ; sdis= ; scon=
        for svri in "$@" ; do           # loop over Xorg arguments
            case "$svri" in
            :[0-9]|:[0-9][0-9])         # found DISPLAY
                sdis="${svri:1}" ;;
            vt[0-9]|vt[0-9][0-9])
                scon="$svri" ;;         # found vt#
            esac
        done

        # add a map entry if DISPLAY and vt# are known
        [ -n "$sdis" -a -n "$scon" ] && smap["$sdis"]="$scon"
    done

    # loop over logged-in users (data from 'who' command)
    local whoa whoi xusr xtty xorg ucur
    local -A umap
    system -a whoa -e -p -r -- who -s || return 1
    for whoi in "${whoa[@]}" ; do
        set -f ; set -- $whoi ; set +f
        xusr="$1" ; xtty="$2" ; xorg="$5"

        # filter for user ...
        if [ "$cons" = 0 ] ; then
            [ "${cusr:-$xusr}" = "$xusr" ] || continue
        fi

        # final state, running Xorg and known vt
        ucur="${umap["$xusr"]}"
        [ "${ucur::2}" = 'vt' ] && continue

        # the user logged in from a tty (or display manager)
        if [ "${xtty::3}" = 'tty' ] ; then
            umap["$xusr"]="$xtty"

        # the user has a vt running Xorg (arg is DISPLAY)
        elif [[ "$xorg" == \(:?\) ]] ; then
            xtty="${xorg//[():]/}"
            xtty="${smap["$xtty"]}"
            if [ -z "$xtty" ] ; then            # Xorg unknown...
                if [ "${ucur::3}" = 'tty' ] ; then
                    # the user is known has runs Xorg but we don't know
                    # the vt number. Assume he is using this tty ...
                    umap["$xusr"]="${ucur/tty/vt}"
                else
                    # we know only that Xorg is running, save DISPLAY ...
                    umap["$xusr"]="$xorg"
                fi
            else
                # got the vt number from Xorg command line ...
                umap["$xusr"]="$xtty"
            fi

        # the user logged in remotely
        elif [ "${xtty::3}" = 'pts' ] ; then
            [ -z "$ucur" ] && umap["$xusr"]="$xorg"
        fi
    done

    # print or return the final result
    for xusr in "${!umap[@]}" ; do
        xtty="${umap["$xusr"]}"
        if [ -z "$cusr" ] ; then
            message -a -p '%-12s  =>  %s' "$xusr" "$xtty"
        else
            # check if console is busy
            if [ "$cons" != 0 ] ; then
                [ "$xtty" = "vt$cons" -o "$xtty" = "tty$cons" ] && cbsy=2
                [ "${cusr:-$xusr}" = "$xusr" ] || continue
            fi
            # return tty and status
            usr_status_="$xtty" ; return "${cbsy:-0}"
        fi
    done
    return 1
}

# ------------------------------------------------------------------------------
# Create file from template: [-n] <vnam> <file> [<pref>]
# ------------------------------------------------------------------------------
set_conf() {
    local odpi="${CEN_OPT_DPI:-96}" curs='24' hash='#' pnts=15 font='fixed'
    local ndpi conf zoom1=1 zoom1=2 scal sdpi="$odpi"
    if [ "$1" = '-n' ] ; then               # keep dpi
        ndpi=1 ; shift
    elif [ "$odpi" -ge 120 ] ; then
        curs='36' ; pnts=20
    fi

    if [ "$CEN_OPT_SCALE" != 0 ] ; then
        scal="$CEN_OPT_SCALE"
        [ "$CEN_OPT_SCALE" = 2 ] && sdpi=$(((odpi * 3 + 2) / 4))
    fi

    zoom1=$((odpi * 100 / 96))
    zoom2=$((odpi *  50 / 96))
    [ "$zoom1" -gt 100 ] && zoom1="${zoom1/[0-9]/&.}" || zoom1=1
    [ "$zoom2" -gt 100 ] && zoom2="${zoom2/[0-9]/&.}" || zoom2=1

    # skip readonly file
    if [ -e "$2" ] && [ ! -w "$2" ] ; then
        warning $"Readonly file skipped:" "$2" ; return 0
    fi

    # map colsolefonts to dpi
    local item cfnt='Terminus' csiz='8x14'
    for item in "${DAT_DPI_CONS[@]}" ; do
        [ "$odpi" -lt "${item%% *}" ] && continue
        cfnt='TerminusBold' ; csiz="${item#* }" ; break
    done

    if [ -d '/usr/share/doc/xfonts-terminus' ] ; then
        pnts=16 ; font='terminus'
    fi
    [ "$2" = "$DAT_XRES" ] && hash='!'                         # use Xresource syntax

    splitjoin -s conf -n -i "$1"
    if [ "${#conf[*]}" -le 1 ] ; then
        warning -p $"Missing configuration template, see '%s'" "$1" ; return 0
    fi

    local line curr data=("$hash autogenerated by '$CEN_NAME' - see '$CEN_DEFAULTS'")
    for line in "${conf[@]}" ; do
        if [ -n "$ndpi" ] ; then
            if [ -n "$3" ] ; then                   # option arg
                curr="${line//%%DPI%%/}"
            else                                    # config line
                curr="${line//%%DPI%%/$odpi}"
                [ "$curr" = "$line" ] || continue
            fi
            line="${curr//%%CURSOR%%/$curs}"
            [ "$curr" = "$line" ] || continue
        else
            curr="${line//%%DPI%%/$3$odpi}"
            line="${curr//%%CURSOR%%/$curs}"
        fi
        line="${line//%%XPNT%%/$pnts}"
        line="${line//%%XFNT%%/$font}"
        line="${line//%%CFONT%%/$cfnt}"
        line="${line//%%CSIZE%%/$csiz}"
        line="${line//%%SCALE%%/$scal}"
        line="${line//%%ZOOM1%%/$zoom1}"
        line="${line//%%ZOOM2%%/$zoom2}"

        # TODO see $3
        line="${line//%%SDPI%%/-dpi $sdpi}"
        data+=("$line")
    done
    outdata -o data -t -- "$2"
    return 0
}

# ------------------------------------------------------------------------------
# switch virtual terminal: -|0|N
# ------------------------------------------------------------------------------
set_console() {
    if [ "${1:--}" = '-' ] ; then
        local sesa sesn sesi
        system -q -a sesa loginctl list-sessions --no-legend || return 1
        for sesn in "${sesa[@]}" ; do
            set -- $sesn
            [ "$2" = "$EUID" ] && continue
            system -e -p loginctl activate "$1" || return 1
            break
        done
    elif [ "$1" != 0 ] ; then
        local ccon
        set_cons_root -s ccon -- fgconsole
        [ -z "$DAT_OCON" ] && DAT_OCON="$ccon"
        [ "$ccon" = "$1" ] || set_cons_root -- chvt "$1"
    fi
    return 0
}

# ------------------------------------------------------------------------------
# run chvt/fgconsole as root if /dev/display is not writable
# ------------------------------------------------------------------------------
set_cons_root() {
    system -q "$@" && return 0
    system -e -p -u - "$@"
}

# ------------------------------------------------------------------------------
# get screen resolution
# ------------------------------------------------------------------------------
set_hres() {
    [ -z "$DAT_CARD" ] && has_display
    local mode=800 mfil="$DAT_CARD/modes"
    [ -r "$mfil" ] && read mode <"$mfil"
    DAT_HRES="${mode%%x*}"
    if [ -n "${DAT_HRES//[0-9]/}" ] ; then
        warning -a $"Unknown video mode:" "$mode" "($DAT_CARD)"
        return 1
    fi
    trace -a -c $"Video monitor-hres" "$DAT_HRES" "($DAT_CARD)"
    return 0
}

# ------------------------------------------------------------------------------
# merge xresources file: <dpi>
# ------------------------------------------------------------------------------
set_xrdb() {
    [ -n "$DISPLAY" ] || return
    [ -r "$DAT_XRES" ] || return
    if [ "$1" = 0 ] ; then
        syspipe -o "grep -v Xft\.dpi $DAT_XRES" -d 'xrdb'
    elif [ "$1" -lt 0 ] ; then
        system -e -p 'xrdb' -merge "$DAT_XRES"
    else
        syspipe -o "sed -e s/^Xft.dpi.*/Xft.dpi:$1/ $DAT_XRES" -d 'xrdb'
    fi
}

# ------------------------------------------------------------------------------
# manage sddm config and Xresources: [-n]
# ------------------------------------------------------------------------------
set_mode() {
    [ -z "$CEN_OPT_MODE" -a -z '$1' ] && return
    local item curr ndpi cdpi

    if [ "$CEN_OPT_DPI" = '-' ] ; then
        ndpi='-n'                                   # don't set dpi at all
        trace $"DPI will not be set"

    elif [ "${CEN_OPT_DPI:-0}" = 0 ] ; then         # get dpi via CEN_OPT_MODE
        for item in "${DAT_DPI_INFO[@]}" '' ; do
                                                    # by screen size ...
            if [ "${CEN_OPT_MODE:--}" = '-' ] ; then
                [ -z "$item" ] && break             # end of list
                if [ -z "$DAT_HRES" ] ; then        # init on 1st pass
                    set_hres || return
                fi
                curr="${item##* }"                  # format is: <name> <hres> <dpi>
                item="${item#* }" ; item="${item%% *}"
                [ "$item" -gt "$DAT_HRES" ] && break
                CEN_OPT_DPI="$curr"
                                                    # mode by name ...
            elif [ "${item%% *}" = "$CEN_OPT_MODE" ] ; then
                CEN_OPT_DPI="${item##* }"
                break

            elif [ -z "$item" ] ; then              # not found
                fatal -t - '--mode'
            fi
        done
        trace -c $"DPI set by mode" "$CEN_OPT_DPI"

    else
        trace -c $"DPI set explicitly" "$CEN_OPT_DPI"
    fi

    if [ -z "$CEN_OPT_SCALE" ] ; then
        if [ "$CEN_OPT_DPI" -ge 190 ] ; then
            CEN_OPT_SCALE=2
        else
            CEN_OPT_SCALE=1
        fi
        trace -a -c $"GTK scaling" "CEN_OPT_SCALE=$CEN_OPT_SCALE"
    fi

    [ "$EUID" = 0 ] || return                       # only root can write to /etc

    if status_file -r ; then
        cdpi="${CEN_DISPLAY_DPI0%-}"
        if [ "$CEN_DISPLAY_SCAL" = 0 ] ; then
            if [ -z "$CEN_OPT_FORCE" ] ; then
                message "Mode is frozen, use '--force --mode=...' to unfreeze"
                return
            fi
            DAT_PERS_CONT=
        elif [ "$CEN_DEFAULTS" -nt "$DAT_PERS" ] ||
             [ "$CEN_TOOLS/$CEN_NAME" -nt "$DAT_PERS" ] ; then
            cdpi= ; DAT_PERS_CONT=
        fi
        if [ "$CEN_OPT_SCALE" = 0 ] ; then
            message "Mode will be frozen"
            CEN_OPT_SCALE="$CEN_DISPLAY_SCAL"       # keep last scaling
            CEN_DISPLAY_SCAL=0 ; status_file -w
        else
            CEN_DISPLAY_SCAL="$CEN_OPT_SCALE"
        fi
        if [ "$CEN_OPT_DPI" = "$cdpi" -a -z "$CEN_OPT_FORCE" ] ; then
            trace -a $"DPI not changed, no config updates" ; return
        fi
    fi

    set_conf $ndpi DAT_CFG_CONSOLE "$DAT_CONSOLE"
    set_conf $ndpi DAT_CFG_LIGHTDM "$DAT_LIGHTDM" '-dpi '
    set_conf $ndpi DAT_CFG_LIGHTDG "$DAT_LIGHTDG"
    set_conf $ndpi DAT_CFG_DISPLAY "$DAT_DISPLAY"
    set_conf $ndpi DAT_CFG_SDDM    "$DAT_SDDM"    '-dpi '
    set_conf $ndpi DAT_CFG_XRES    "$DAT_XRES"

    system -w systemctl restart console-setup.service
    CEN_DISPLAY_DPI0="$CEN_OPT_DPI"
    [ "$CEN_OPT_SCALE" != 0 ] && status_file -w
}

# ------------------------------------------------------------------------------
# start Xorg Server or wayland
# ------------------------------------------------------------------------------
run_guiserver() {
    system -e -q -r -- touch -d "+ $tmax seconds" "${DAT_TEMP}_term"

    # fix runtime dir ...
    if [ -z "$XDG_RUNTIME_DIR" ] ; then
        XDG_RUNTIME_DIR="/run/user/$EUID"
        [ -d "$XDG_RUNTIME_DIR" ] || XDG_RUNTIME_DIR="$TMP"
        export XDG_RUNTIME_DIR
    fi

    local opts disp xdpi="$CEN_OPT_DPI"

    case "$CEN_OPT_SERVER" in
    xinit)  if [ -e ~/'.Xauthority' ] ; then        # otherwise let startx create one
                [ -e ~/'.xinitrc' ] &&
                    opts+=(~/'.xinitrc') || opts+=('/etc/X11/xinit/xinitrc')
                # Automatically determine an unused $DISPLAY
                disp=0
                while true ; do
                    [ -e "/tmp/.X$disp-lock" -o -S "/tmp/.X11-unix/X$disp" ] || break
                    ((disp += 1))
                done
            else
                CEN_OPT_SERVER='startx'
            fi
            ;;
    startx) ;;
    *)      fatal "Not implemented:" "$CEN_OPT_SERVER"
    esac

    opts+=('--')
    [ -n "$disp" ] && opts+=(":$disp")
    if [ -n "$xdpi" ] ; then
        [ "$CEN_OPT_SCALE" = 2 ] && xdpi=$(((xdpi * 3 + 2) / 4))
        opts+=('-dpi' "$xdpi")
    fi
    [ "${CEN_OPT_CONSOLE:-0}" -gt 0 ] &&
        opts+=("vt$CEN_OPT_CONSOLE") || opts+=('-keeptty')

    message "Running:" "$CEN_OPT_SERVER" "${opts[@]}" "$@"
    if dryrun -s "$CEN_OPT_SERVER" "${opts[@]}" "$@" ; then
        timer -w 3
    else
        system -x -e -- "$CEN_OPT_SERVER" "${opts[@]}" "$@"
        [ -n "$DAT_OCON" ] && set_console "$DAT_OCON"
    fi
}

# ------------------------------------------------------------------------------
# Start a display manager: <prog>
# ------------------------------------------------------------------------------
run_displaymgr() {
    has_issue                               # wait until finished
    case "$1" in
    auto)   system -c 'sddm' && set -- 'sddm' || set -- 'lightdm'
            ;;
    sddm|lightdm)
            ;;
    *)      return 1
    esac

    PATH+=':/usr/sbin'
    system -c "$1" || fatal -p $"Display-Manager '%s' not found" "$1"
    has_display ; set_mode                  # wait for monitor, set dm config
    system -x -f "$1" ; return 0            # does not return unless --dry
}

# ------------------------------------------------------------------------------
# The one and only action
# ------------------------------------------------------------------------------
run() {
    local unam="$CEN_OPT_USER"

    # Option -R : run with xresources applied, restore without Xfi.dpi (for KDE)
    if [ -n "$CEN_OPT_RUN" ] ; then
        system -f -p -- xrdb "$DAT_XRES"
        set_xrdb -1                         # merge font resources
        $CEN_OPT_RUN & sleep 3
        set_xrdb 0                          # ignore Xft.dpi
        wait ; return

    # Option -I : list input
    elif [ -n "$CEN_OPT_INPUT" ] ; then
        has_input ; return

    # Option -L : list users and return status (3:=tty  4:=xorg  5:unknown)
    elif [ -n "$CEN_OPT_LIST" ] ; then
        usr_status "$CEN_OPT_LIST"
        [ "$CEN_OPT_LIST" = '-' ] && return
        case "$usr_status_" in
        tty*)   message -a -p $"User '%s' uses terminal '%s'" "$unam" "$usr_status_"
                error -s 3 ;;
        vt*)    message -a -p $"User '%s' uses console '%s'" "$unam" "$usr_status_"
                error -s 4 ;;
        '')     message -a -p $"No local login found for user '%s'" "$unam" ;;
        *)      message -a -p $"User '%s' is logged in at '%s'" "$unam" "$usr_status_"
                error -s 5 ;;
        esac
        return

    elif [ -n "$CEN_OPT_XRES" ] ; then
        set_xrdb "$CEN_OPT_XRES"
        return

    # Option -S none : return display status (5 := no display)
    elif [ "$CEN_OPT_SERVER" = 'none' ] ; then
        has_display ; quit -s $?            # exit with status

    # Option -S chvt : switch display
    elif [ "$CEN_OPT_SERVER" = 'chvt' ] ; then
        usr_status "$unam"
        case "$usr_status_" in
        tty*) set_console "${usr_status_:3}" ; return ;;
        vt*)  set_console "${usr_status_:2}" ; return ;;
        *)    if [ -n "$CEN_OPT_CONSOLE" ] ; then
                 set_console "$CEN_OPT_CONSOLE"
              else
                 error -p $"Cannot find console for user '%s'" "$unam"
              fi
        esac
        return

    # Start a display manager
    elif run_displaymgr "$CEN_OPT_SERVER" ; then
        return

    elif [ -n "$CEN_OPT_MODE" ] ; then
        set_mode
    fi

    # starting server ...
    [ -z "$CEN_OPT_SERVER" ] && return
    if [ -z "$CEN_OPT_FORCE" ] ; then
        usr_status "$unam" "$CEN_OPT_CONSOLE"
        if [ $? = 2 ] ; then
            error -p $"Console 'vt%s' is busy - not runnig '%s'" \
                     "$CEN_OPT_CONSOLE" "$CEN_OPT_SERVER"
            error -s 127; return
        fi
        case "$usr_status_" in
        tty*)   if [ -z "$CEN_OPT_CONSOLE" -a ! '/dev/stdin' -ef "/dev/$usr_status_" ] ; then
                    error -p $"User '%s' uses terminal '%s' - not runnig '%s'" \
                          "$unam" "$usr_status_" "$CEN_OPT_SERVER"
                    error -s 127; return
                fi ;;
        vt*)    error -p $"User '%s' uses console '%s' - not runnig '%s'" \
                          "$unam" "$usr_status_" "$CEN_OPT_SERVER"
                error -s 127; return
        esac
    fi

    [ -n "$CEN_DISPLAY" ] && quit -e $"Cannot be run from a graphical session"
    message -a "$CEN_TITLE"
    has_display
    message -a $"Display detected"
    [ "$CEN_OPT_DPI" = 0 ] && set_mode -n   # get dpi value from monitor resolution
    [ "$CEN_OPT_DPI" = 0 ] && CEN_OPT_DPI=

    folder -s DAT_TEMP -t ''                # prefix for temporary files
    [ -n "$DAT_TEMP" ] || DAT_TEMP=".$CEN_NAME"

    local tcur=0 tmax=10
    system -e -p -r -- touch "${DAT_TEMP}_start"
    while [ "${DAT_TEMP}_term" -nt "${DAT_TEMP}_start" ] ; do
        message -a $"Deferring X-Server startup"
        timer -w 3 ; ((tcur += 3))
        system -e -p -r -- touch "${DAT_TEMP}_start"
        [ "$tcur" -lt "$tmax" ] || break
    done

    local csta ccon cset cfgn='-n'
    if [ "$CEN_OPT_CONSOLE" = 0 ] ; then
        cset=1 ; CEN_OPT_BACKGROUND=
        set_cons_root -r -s ccon -- fgconsole
        [ -n "$ccon" ] && CEN_OPT_CONSOLE="$ccon"
    elif [ -n "$CEN_OPT_BACKGROUND" ] ; then
        cfgn=
    fi

    message -a -p $"Starting X-Server, console=%s" "${CEN_OPT_CONSOLE:-$"<current>"}"
    if [ -z "$cfgn" ] ; then
        [ -x '/usr/lib/xorg/Xorg.wrap' ] || quit -e \
            $"Cannot run in background without XWrapper (xorg-xserver-legacy) installed"
    #    [ -n "$CEN_OPT_CONSOLE" ] && set_console "$CEN_OPT_CONSOLE"
        background -m 'old' -o '.xsession-errors' run_guiserver ; csta=$?
    else
    #    [ -n "$CEN_OPT_CONSOLE" ] && set_console "$CEN_OPT_CONSOLE"
        run_guiserver &>'.xsession-errors' ; csta=$?
    fi

    if [ -n "$CEN_OPT_BACKGROUND" ] ; then
        message -a -p $"Started X-Server (status=%s)" "$csta"
        timer -w 1
    else
        message -a -p $"Terminated X-Server (status=%s)" "$csta"
        [ -n "$cset" ] && set_console           # was -C0, back to Xorg
    fi
}

# ------------------------------------------------------------------------------
# implement option parsing: <option> <argument>
# ------------------------------------------------------------------------------
options() {
    local   nock
    case "$CEN_ACTION" in
    '')
        # program to run (default is $DAT_GUI), check if existing
        case "$CEN_OPT_SERVER" in
        '')
            # imply --server=xxxx with --console
            [ -z "$CEN_OPT_MODE" -o -n "$CEN_OPT_CONSOLE" ] && CEN_OPT_SERVER="$DAT_GUI"
            # imply ---mode=- with --scale=N
            if [ -z "$CEN_OPT_MODE" -a "$CEN_OPT_SCALE" != 0 ] ; then
                [ -n "$CEN_OPT_SCALE" ] && CEN_OPT_MODE='-'
            fi
            ;;
        none|auto|sddm|lightdm)
            nock=1 ;;
        kiosk)
            CEN_OPT_SERVER="$DAT_GUI"
        esac
        [ -n "$CEN_OPT_SERVER" -a -z "$nock" ] && system -c -f -- "$CEN_OPT_SERVER"

        # run as another user ...
        local unam="${USER:-$LOGNAME}"
        [ "${CEN_OPT_USER:--}" = '-' ] && CEN_OPT_USER="$unam"
        if [ "$CEN_OPT_USER" != "$unam" ] ; then
            message -a -p "Current user '%s' want '%s'" "$unam" "$CEN_OPT_USER"
            context -r                              # we must be root
            # create temporary /etc/XWrapper.conf config override (see centaurisysinit)
            local wrap="${CEN_PATHS[2]}/X11/Xwrapper.config"
            if [ -f "$wrap" ] && [ ! -f "$wrap.default" ] ; then
                move -q -x -- "$wrap" "$wrap.default"
                create -h - -- "$wrap" <<!EOF

# We need this to have user access to tty and keyboard. At next boot the
# centaurisysinit service will restore the saved /etc/X11/Xwrapper.conf:

needs_root_rights=yes
allowed_users=anybody
!EOF
            fi

            set -- "$0" "${CEN_CMDOPTS[@]}" "${CEN_CMDARGS[@]}"
            trace -a -c $"Rerun as user" -- "$CEN_OPT_USER:" "$*"
            if system -c setpriv ; then
                # re-run via setpriv
                local egrp ; system -s egrp -f -p -- id -g "$CEN_OPT_USER"
                eval folder -c -f ~"$CEN_OPT_USER"
                local opts=("--reuid=$CEN_OPT_USER" "--regid=$egrp" \
                            --init-groups --reset-env "$BASH" -l "$@")
                trace -a -c $"Rerun" -- 'setpriv' "${opts[@]}"
                exec setpriv "${opts[@]}"
            else
                # re-run via su (not sudo, context -u would do sudo)
                local sexe="${@@Q}"
                trace -a -c $"Rerun" -- "su -l -c \"$sexe\" $CEN_OPT_USER"
                exec su -l -c "$sexe" "$CEN_OPT_USER"
            fi
            fatal $"Could not exec as '$CEN_OPT_USER'"
        fi
        trace -a -c $"Running as" -- "$unam"
        ;;

    -A|--sca*)
        optarg 'scale'      - '[012]' ;;
    -B|--bac*)
        optarg 'background' -    ;;     # flag
    -C|--con*)
        optarg 'console'    - -n ;;     # console#
    -D|--dpi)
        optarg 'dpi'        - -n ;;     # number
    -I|--inp*)
        optarg 'input'      -    ;;     # flag
    -L|--lis|--list)
        optarg 'list'       - -t ;;     # text
    -M|--mod|--mode)
        optarg 'mode'       - 'sd|pc|hd|4k|5k|-' ;;
    -N|--now*)
        optarg 'nowait'     -    ;;     # flag
    -R|--run*)
        optarg 'run'        - -t ;;     # text
    -S|--ser*)
        optarg 'server'     - -t ;;     # text
    -U|--use|--user)
        optarg 'user'       - -t ;;     # text
    -X|--xre*)
        optarg 'xres'       - -n ;;     # number

    esac
}

# ------------------------------------------------------------------------------
# print usage info
# ------------------------------------------------------------------------------
usage() {
    usageset \
        -o - \
        -o '-A --scale   <scal>'  $"used as DPI divisor, scale factor for GTK" \
        -o '-B --background'      $"do not wait for server (unless **--console=0**)" \
        -o '-C --console <cnum>'  $"check if console is free, run on this console" \
        -o '-D --dpi     <dpi>'   $"fixed DPI for X-Server (can be reset with --mode)" \
        -o '-I --input'           $"list touch/keyboard input devices" \
        -o '-L --list    <what>'  $"list users and ttys only, don't start server" \
        -o '-M --mode    <mode>'  $"autoconfigure display-manager for monitor" \
        -o '-N --nowait'          $"do not wait for a display to be connected" \
        -o '-S --server  <prog>'  $"program to run, default is:"" 'startx'" \
        -o '-U --user    <user>'  $"run as a different user" \
        -o '-X --xres    <xres>'  $"explicitly merge"" '$DAT_XRES'" \

    usageset \
        -p '<cnum>'      $"console to use  -or- '0' for current console without check" \
        -p '<dpi>'       $"DPI value passed to server <prog> (not for lightdm/sddm)" \
        -p '<mode>'      $"monitor resolution: 'pc|sd|hd|4k' use '-' for autodetect" \
        -p '<what>'      $"can be a user-name or '-' for everyone" \
        -p '<prog>'      $"program to run:"' none|chvt|auto|startx|sddm|lightdm|<path>' \
        -p '<scal>'      $"scale factor, can be: 0 (disable), 1 (default) or 2" \
        -p '<user>'      $"a user name  -or-  '-' to disable check" \
        -p '<xres>'      $"set Xft.dpi:  -1 (leave out)  0 (from file)  <dpi> (override)" \

    usageset \
        -e "$CEN_NAME -C 0                    # startx for current user and console" \
        -e "$CEN_NAME -C 10 -D 125            # startx at vt10, override dpi value" \
        -e - \
        -e "$CEN_NAME -U otto                 # start XServer for otto" \
        -e "$CEN_NAME -U otto -S none         # test if otto is logged in" \
        -e "$CEN_NAME -U otto -S chvt         # switch to ottos's console" \
        -e - \
        -e "$CEN_NAME -M -                    # auto-update configuration" \
        -e "$CEN_NAME -M - -A0                # update configuration and freeze" \
        -e "$CEN_NAME -M - -f                 # unfreeze and update configuration" \
        -e - \
        -e "$CEN_NAME -N                      # just test for connected display" \
        -e "$CEN_NAME -S none -v              # just wait for connected display" \
        -e "$CEN_NAME -S auto                 # wait and start lightdm or sddm" \
        -e "$CEN_NAME -S lightdm -M -         # wait and start lightdm, autoconfig" \
        -e "$CEN_NAME -S sddm -M hd -D 132    # ... override DPI setting"

    usageset \
        -l $"configuration" \
        -t "# $CEN_ROOT/default/$CEN_NAME can be used to preset options:" \
        -t "[ -z \"\$CEN_OPT_DPI\" ] && CEN_OPT_DPI=132" \
        -t "[ -z \"\$CEN_OPT_MODE\" ] && CEN_OPT_MODE=hd" \

    usagecat << !EOF
$CEN_USE_HEADER

$CEN_USE_OPTIONS

$CEN_USE_PARAMS

$CEN_USE_EXAMPLE

$CEN_USE_OTHER
!EOF
    usagecat -v $"more:  Use -- to show configuration details." << !EOF
remarks:
       If the users home folder has no .xinitrc the default x-session ist started
       (change the default via update-alternatives --display x-session-manager).
       This behaviour can be overridden by creating a custom .xinitrc. Example:

            #!/usr/bin/bash
            dbus-launch ; kwin &
            setxkbmap -option srvrkeys:none

            prog="/usr/bin/konsole"
            args="--nofork"
            mesg="Programm nicht gefunden: \$prog"

            if [ -x "\$prog" ] ; then
                mesg=
                \$prog \$args || mesg="Fehlerende (status \$?): \$prog"
            fi
            [ -n "\$mesg" ] && kdialog --error "\$mesg"

       This can be combined with autologin. In the following unit file at
       /etc/systemd/system/getty.target.wants//getty@tty6.service :

            [Unit]
            Description=Autologin user surf at %I
            After=systemd-user-sessions.service plymouth-quit-wait.service
            After=rc-local.service
            Before=getty.target
            IgnoreOnIsolate=yes
            ConditionKernelCommandLine=autologin
            [Service]
            ExecStart=-/sbin/agetty --autologin surf --noclear %I $TERM
            Type=idle
            Restart=always
            RestartSec=0
            UtmpIdentifier=%I
            TTYPath=/dev/%I
            TTYReset=yes
            TTYVHangup=yes
            TTYVTDisallocate=yes
            KillMode=process
            IgnoreSIGPIPE=no
            SendSIGHUP=yes
            [Install]
            WantedBy=getty.target
            DefaultInstance=tty6
!EOF
}

# ------------------------------------------------------------------------------
# Finally call the library to execute the script
# ------------------------------------------------------------------------------
main "$@" ; quit

# the end
