#!/usr/bin/bash
# ------------------------------------------------------------------------------
CEN_LEGAL="Dr. J. Pfennig (c) 2024-2025; all rights reserved"
CEN_TITLE=$"An extendable HTML based Day-Time-Clock"

# Import the bash library
PATH+=":${0%/*}" . _centauri_bash_lib -a -d -g -o 'centauriclock' '0.16:5' || exit 2

#context -v 2                       # debug output

# Options and data

CEN_OPT_BASE=                       # base folder
CEN_OPT_EXEC=                       # startup tool
CEN_OPT_HTML=                       # HTML file
CEN_OPT_INVERT=                     # coordinate inversion
CEN_OPT_LANG=                       # language
CEN_OPT_SCALE=                      # scaling
CEN_OPT_TIMER=                      # timer

DAT_DPMS_OFF=                       # see actionTimer
DAT_UNCLUTTER=

# started as an appliance?

if [ "${BASH_ARGV0##*/}" = '.centauristartup' ] ; then
    CEN_OPT_BASE='-' ;  CEN_OPT_TIMER=1
    [ $# = 0 ] && set -- run --gui=0
fi

DAT_BASEDIR="~/.local/$CEN_NAME"    # defaults ...
DAT_HTMLTXT="$CEN_NAME.html"

# We prefer a tabular font and googles's 'noto' is the best known.
# If it is installed on this computer we can safely use 10vw size...
if [ -d '/usr/share/fonts/truetype/noto' ] ; then
    DAT_SIZEPNT='10vw'              # 'noto' font is smaller than others
# other fonts tend to renders larger ...
else
    DAT_SIZEPNT='8.8vw'             # conservative choice
fi

DAT_STARTUP="./${CEN_NAME}.bash"
DAT_LANGGUI='en'

if [ -z "$LANG" ] ; then            # get system default ...
    embed -b -n "$CEN_DEFAULT/locale" &&
        DAT_LANGGUI="${LANG::2}"    # intentionally ignore *_US* here
else
    case "${LANG,,}" in             # get internal language code...
    *_us*)  DAT_LANGGUI='us' ;;
    *)      DAT_LANGGUI="${LANG::2}"
    esac
fi

# ------------------------------------------------------------------------------
# Create clock html: <path>
# ------------------------------------------------------------------------------
create_html() {
    create -f -c -- "$1" <<!EOF
<!DOCTYPE html>
<html lang="en" class='croot'>
<head>
  <meta charset="UTF-8">
  <title>JavaScript Digital Clock</title>
  <style>
    body {
      margin: 0;
      padding: 0;
      height: 100vh;
    }

    /* layout is based on unit 'rem', so font and font-size must be set here */
    .croot {
      /* Noto Sans: is a tabular font and can be downloaded from Google, it is
            not installed by default.
         Quicksand: very nice font, but not tabular. This is why we use two
            cells to display hour and minute.
         sans-serif: used as a fall-back (typically aliased to 'DejaVu Sans'.

         font-size: use '10vw' for nice automatic scaling on 16:9 displays
      */
      font-family: "Noto Sans", "Quicksand", "sans-serif";
      font-size: 10vw;
      font-variant-numeric: tabular-nums;
      overflow: hidden;
    }

    .cclock {
      width: 100%;
      height: 100%;
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      background-color: black;
    }

    .ctime {
      font-size: 3.9rem;
      font-weight: bold;
      color: #ccf;
      margin-top: calc(3vh - 2rem);
      /* margin-top: -15vh;   set via dom when no temperatures are shown */
      margin-bottom: calc(15vh - 1.5rem);
    }

    .cdigit {
      display: inline-block;
      width: 46vw;
    }

    .cdsepa {
      display: inline-block;
      font-size: 2.5rem;
      line-height: 0.6rem;
      width: 6vw;
    }

    .csecs {
        color: #00ffff;
        width: 95%;
        margin-bottom: calc(20vh - 1.2rem);
    }

    .csecs-bar {
        height: 0.12rem;
        background-color: beige;
        /* it seems that only 'px' is working here */
        border-radius: 0.1rem;
    }

    .cidate {
      color: #aff;
      font-size: 0.6rem;
      text-align: center;
      margin-top: calc(20vh - 0.8rem);
    }
    .citemp {
      color: #aff;
      margin-bottom: -10vh;
      margin-bottom: calc(-18vh + 0.3rem);
    }

    .ctemp {
      position: absolute;
      /* justify-content: center; */
      font-size: 1.8rem;
      text-align: right;
    }

    .cdate {
      display: inline-block;
      font-size: 0.65rem;
      line-height: 0.7rem;
      margin-top: 9vh;
      margin-top: calc(8vh - 0.1rem);
      margin-top: calc(6vw - 0.2rem);
      text-align: center;
    }
    .cdegr {
      position: absolute;
      justify-content: top;
      margin-top: 2vh;
      font-size: 0.9rem;
    }

  </style>
</head>

<body>
  <div class="cclock">
    <div class="ctime">
        <span id="ahour" class="cdigit" style="text-align: right;">--</span><span id="asepa" class="cdsepa">:</br>&nbsp;</span><span id="aminu" class="cdigit">--</span>
    </div>
    <div class="csecs"><div id="asecs" class="csecs-bar"></div></div>
    <div class="cidate" hidden></div>
    <div class="citemp">
        <span class="ctemp" style="right: 80vw"><span id="atmp1"></span><span class="cdegr" id="adeg1">°</span></span>
        <span class="cdate" id="adate"></span>
        <span class="ctemp" style="right: 4vw"><span id="atmp2"></span><span class="cdegr" id=adeg2>°</span></span>
    </div>
  </div>

<script>
var centauriclock_data='';     // CORS http url to load data, use file if empty
var temperature_inside='--';
var temperature_outside='--';
</script>
<script src='centauriclock.js'></script>
<script>

// query parameter: language and font scaling
var lang='de'
var ourl = window.location.search.substring(1);
var aurl = ourl.split('&');
for (var indx = 0; indx < aurl.length; indx++)
{ var kval = aurl[indx].split('=');
  switch(kval[0]) {
    case 'lang':
      lang = kval[1].substring(0,2)
    case 'rsiz':
      document.querySelector('.croot').style.fontSize = kval[1];
  }
}
delete ourl; delete aurl; delete kval; delete indx

// more global variables
var htmld = document.firstElementChild;
htmld.setAttribute('onkeydown', 'keydown(event)');
htmld.setAttribute('ontouchstart', 'touch(event)');

var vhour = document.getElementById("ahour");
var vminu = document.getElementById("aminu");
var vdate = document.getElementById("adate");
var vtmp1 = document.getElementById("atmp1");
var vtmp2 = document.getElementById("atmp2");
var vdeg1 = document.getElementById("adeg1");
var vdeg2 = document.getElementById("adeg2");

// store day and month name in an array
switch (lang) {
  case 'de':
    var dayNames = 'Montag Dienstag Mittwoch Donnerstag Freitag Sonnabend Sonntag';
    var monthNames = 'Januar Februar März April Mai Juni ' +
                     'Juli August September Oktober November Dezember ' +
                     '- - - - - - - - Sept. Okt. Nov. Dez.'; break;
  case 'fr':
    var dayNames = 'Lundi Mardi Mercredi Jeudi Vendredi Samedi Dimanche';
    var monthNames = 'Janvier Février Mars Avril Mai Juin ' +
                     'Juillet Août Septembre Octobre Novembre Décembre'; break;
  default:
    var dayNames = 'Monday Tuesday Wednesday Thursday Friday Saturday Sunday';
    var monthNames = 'January February March April May June ' +
                     'July August September October November December ' +
                     'Jan Feb Mar Apr - Jun Jul Aug Sep Oct Nov Dec';
}
dayNames = dayNames.split(' ')
monthNames = monthNames.split(' ')

// get progress bar element
var sbar = document.getElementById("asecs");
var last_minutes

function updateClock() {
  // Get the current time, day , month and year
  var now = new Date();
  var minutes = now.getMinutes();
  var seconds = now.getSeconds();

  sbar.style.width = (seconds * 100 / 59) + '%';
  if ( minutes == last_minutes ) return
  last_minutes = minutes

  var hours = now.getHours();
  var day = now.getDay();               // BEWARE: 0:=sunday WHY THE HELL!
  var date = now.getDate();
  var month = now.getMonth();
  var year = now.getFullYear();

  // fix the idiotic day-of-week according to ISO standard
  day = day > 0 ? day - 1 : 6

  // format date and time
  minutes = minutes < 10 ? '0' + minutes : minutes;
  seconds = seconds < 10 ? '0' + seconds : seconds;

  // display date and time
  var line1 = dayNames[day] ; var line2 = monthNames[month]
  if (temperature_outside != '--' && monthNames[month+12] != '-') {
    line2 = monthNames[month+12] ?? line2
  }

  switch (lang) {
    case 'de': line2 = date + '. '+ line2 + ' ' + year; break;
    case 'en': line2 = date + ' ' + line2 + ' ' + year; break;
    case 'fr': line1 = line1 + ' ' + date; line2 = line2 + ' ' + year; break;
    case 'us': hours = hours % 12 || 12;
               line2 = date + ' ' + line2 + ' ' + year; break;
    default:  line1 = dayNames[day];
              month = (month < 9) ? '0' + (month+1) : month + 1;
              data = (date < 10) ? '0' + date : date;
              line2 = year + '-' + month + '-' + date;
  }

  vhour.innerHTML = hours; vminu.innerHTML = minutes;

  if (temperature_outside == '--') {
    document.querySelector('.cidate').innerHTML = line1 + ' ' + line2;
  } else {
    vdate.innerHTML = line1 + '</br>' + line2;
  }

  // load temperatures from server via http
  if (centauriclock_data != '') {
    fetch(centauriclock_data)
      .then(x => x.text())
      .then(y => updateTemp(y));
  }
}

function updateTempDisp(eltt, eltd, temp) {
   var color
   if (temp == '' || temp == '-') {
     temp='--';
   }
   else if (temp.substring(0,1) == '-') {
     temp = -Math.round(temp);
     color = '#66f';
   }
   else {
     temp = Math.round(temp);
     color = '#f88';
  }
  eltt.innerHTML = temp;
  eltt.style.color=color; eltd.style.color=color;
}

function updateTemp(text) {
  eval(text)
  updateTempDisp(vtmp1, vdeg1, temperature_outside)
  updateTempDisp(vtmp2, vdeg2, temperature_inside)
}

// keys q/Escape and touch are handled in qml code via console logging
function keydown(event) {
  switch(event.key) {
    case 'd': vhour.innerHTML=44; vminu.innerHTML=44;
    updateTempDisp(vtmp1, vdeg1, -44);
    updateTempDisp(vtmp2, vdeg2, 44);
    break;
    case 'f': console.log("FULL"); break;
    case 'w': console.log("WIND"); break;
    case 'q':
    case 'Escape': console.log("QUIT"); break;
  }
}
function touch(event) {
  console.log("EXIT") ;
}

// load temperatures from via file using refresh
if (centauriclock_data == '') {
  // disable temperature display (no data file)
  if (temperature_outside == '--') {
    document.querySelector('.citemp').style.display='none'
    document.querySelector('.cidate').style.display='block'
    document.querySelector('.ctime').style.marginTop='-25vh';
    document.querySelector('.ctime').style.marginBottom='-8vh';
  } else {
    setTimeout(function() { location.reload(); }, 300000);
    updateTempDisp(vtmp1, vdeg1, temperature_outside);
    updateTempDisp(vtmp2, vdeg2, temperature_inside);
  }
}

// main script part ...
updateClock();
setInterval(updateClock, 1000);

</script></body>
!EOF
}

# ------------------------------------------------------------------------------
# action html: <file>|<folder>|-
# ------------------------------------------------------------------------------
actionHtml() {
  local surl="${1:-.}"
  [ "$surl" = '.' ] && surl="$PWD"
  [ -d "$surl" ] && surl+="/$DAT_HTMLTXT"
  confirm -y -f $"Extract clock HTML to '%s'" "$surl" || quit -t
  remove -f -- "$surl" ; create_html "$surl"
}

# ------------------------------------------------------------------------------
# action run: -no args-
# ------------------------------------------------------------------------------
actionRun() {
    export XDG_CURRENT_DESKTOP=xinit

    # detect raspberry pi display (old version)
    if [ -z "$CEN_OPT_INVERT" -a -e '/sys/class/backlight/10-0045/brightness' ] ; then
        CEN_OPT_INVERT=1
        message -a $"Assuming input coordinates to be inverted"
    fi

    [ "$CEN_OPT_INVERT" = 1 ] && sysrun -e xinput set-prop 'Virtual Core Pointer' \
                                'Coordinate Transformation Matrix' 0 -1 1  0 -1 1  0 0 1

    if system -c unclutter ; then
        # beware: only system() can be used in a sub-shell
        system -e -x unclutter &
    else
        warning $"Please install 'unclutter' to hide the mouse cursor"
    fi

    local stmp surl

    # configuration folder
    if [ "$CEN_OPT_BASE" = '-' ] ; then
        eval CEN_OPT_BASE="$DAT_BASEDIR"
        folder -f -m -c -- "$CEN_OPT_BASE"
        surl="$DAT_HTMLTXT"
    else
       [ -z "$CEN_OPT_BASE" ] && eval CEN_OPT_BASE="$DAT_BASEDIR"
    fi
    if folder -q -c -- "$CEN_OPT_BASE" ; then
        surl="$DAT_HTMLTXT"
    else
        warning $"Missing configuration:" "$CEN_OPT_BASE"
        surl=
    fi
    if [ -z "$surl" ] ; then
        if [ "${DAT_HTMLTXT::1}" = '/' ] ; then
            surl="$DAT_HTMLTXT"
        else
            tmpfile -f -b - -n -s stmp ; surl="${stmp%/*}/${DAT_HTMLTXT##*/}"
        fi
    fi
    create_html "$surl"

    # run startup tool

    [ -n "$CEN_OPT_EXEC" ] && DAT_STARTUP="$CEN_OPT_EXEC"

     # without --exec the startup tool is optional
    if PATH=".:$PATH" system -c "$DAT_STARTUP" ; then
        trace -a -c $"Run startup tool" "$DAT_STARTUP"
    elif [ -z "$CEN_OPT_EXEC" ] ; then      # no startup skript ...
        DAT_STARTUP='false'
        trace -a $"No startup tool to be executed"
    fi

    # this can intentionally be fatal if --exec=<tool> is invalid
    if [ "$DAT_STARTUP" != 'false' ] ; then
        sysrun -g 1 -f -p -- "$DAT_STARTUP" || quit -- $"Stopped by startup tool"
    fi

    local args=( '-A' "lang=${CEN_OPT_LANG:-$DAT_LANGGUI}"
                 '-A' "rsiz=${CEN_OPT_SCALE:-$DAT_SIZEPNT}"
                 'viewer' "$surl"
               )

    # start timer, run in background, no cleanups
    if [ "$CEN_OPT_TIMER" = 1 ] ; then
        sysrun -q systemd-run --user --on-calendar='*-*-* *:00:20' "$CEN_NAME" timer &
        disown $!                                       # avoid hanging on startup
        DAT_DPMS_OFF='dpms off --' ; actionTimer &
        quit -h                                         # must run quit hooks ...
        embed -x -v -z centaurilauncher --terminal "${args[@]}"
    fi

    # ... other user (no background, no timer)
    embed -v -z centaurilauncher --terminal "${args[@]}"
    if [ "$DAT_STARTUP" != 'false' ] ; then
        message "Terminating workers ..."
        sysrun -e -p -- pkill -s0 -A        # ouch...
    fi
}

# ------------------------------------------------------------------------------
# timer call: -no args-
# ------------------------------------------------------------------------------
actionTimer() {
    local hour zone
    local bval=( 10  10  10  10  10  10 \
                 20  40  50  60  70  70 \
                 70  70  70  60  60  50 \
                 50  40  30  30  20  20 )
    printf -v hour "%(%H)T" -1 ; [ "$hour" != 0 ] && hour="${hour#0}"
    printf -v zone "%(%Z)T" -1
    [ "$zone" = 'CEST' ] || ((hour += 1))
    trace $"Brightness timer:" "$zone ${hour}h -> ${bval[hour]}"
    embed -v -z centauripower --force $DAT_DPMS_OFF brightness "${bval[hour]}"
}

# ------------------------------------------------------------------------------
# option parsing: <option> [<argument>]
# ------------------------------------------------------------------------------
options() {
    case "$1" in
    '') [ -n "$CEN_OPT_HTML" ] && DAT_HTMLTXT="$CEN_OPT_HTML"
        ;;
    -B|--bas|--base)
        optarg 'base'           -    -t ;;          # text
    -E|--exe*)
        optarg 'exec'           -    -t ;;          # text
    -H|--htm|--html)
        optarg 'html'           -    -t ;;          # text
    -I|--inv*)
        optarg 'invert'         -    -o ;;          # on|off|auto
    -L|--lan*)
        optarg 'lang'           -    -t ;;          # text
    -S|--sca*)
        optarg 'scale'          -    -t ;;          # text
    -T|--tim*)
        optarg 'timer'          -    -o ;;          # on|off|auto

    esac
}

# ------------------------------------------------------------------------------
# action parsing: <verb> <argument>...
# ------------------------------------------------------------------------------
actions() {
    case "$1" in
    htm|html)
        invoke 'html'   -           0 1 ;;      # one optional arg
    run)
        invoke 'run'    -           0   ;;      # no args
    tim*)
        invoke 'timer'  -           0   ;;      # no args
    esac
}

# ------------------------------------------------------------------------------
# print usage info
# ------------------------------------------------------------------------------
usage() {
    usageset \
        -h '' \
        -h $"The clock can work stand-alone, using internal HTML-code. For display" \
        -h $"it runs \"centaurilauncher\" and to adjust display brightness following" \
        -h $"the day-time it uses \"centauripower\" via systemd timer." \
        -h '' \
        -h $"Optionally or if run as an appliance (see \"centauristartup\") a config" \
        -h $"folder can be used to provide different HTML-code or to run a tool at" \
        -h $"startup, example: display additional weather information." \

    usageset \
        -o - \
        -o '-B --base    <fldr>' $"Set configuration folder (default: $DAT_BASEDIR)" \
        -o '-E --exec    <tool>' $"Optional startup tool    (default: $DAT_STARTUP)" \
        -o '-H --html    <html>' $"Override configured HTML (default: $DAT_HTMLTXT)" \
        -o '-I --invert  <mode>' $"Invert mouse/touch input coordinates" \
        -o '-L --lang    <code>' $"Override language to use (default: $DAT_LANGGUI)" \
        -o '-S --scale   <pnts>' $"Font and layout scaling  (default: $DAT_SIZEPNT)" \
        -o '-T --timer   <mode>' $"Use of a systemd-timer to control brightness" \

    usageset \
        -p '<code>'              $"Supported are: \"de\" \"en\" \"fr\" (24h) and \"us\" (12h)" \
        -p '<fldr>'              $"Path of configuration and data folder" \
        -p '<html>'              $"Path to the HTML file that gets shown" \
        -p '<mode>'              $"Use one of: on|1  off|0  auto (default)" \
        -p '<pnts>'              $"Font size used as reference for scaling" \
        -p '<tool>'              $"Tool/script executed at startup, \"-\" to ignore" \

    usageset \
        -a 'html  [<path>]'      $"extract HTML code to folder or file (see --html)" \
        -a 'run'                 $"start clock (implied for '.centauristartup' symlink)" \
        -a 'timer'               $"used by brightness timer to run 'centauripower'" \

    usageset \
        -t $"Action \"run\" executes <tool> at startup (if existing). This is used to" \
        -t $"initialize the environment. If <tool> returns an error execution stops." \
        -t $"" \
        -t $"A non-existing \"$DAT_BASEDIR\" is ignored, using \"--base=-\"" \
        -t $"would initialize the folder. Option \"--timer=on\" causes the clock to"\
        -t $"run in background. In appliance mode \"--base=-\" and \"--timer=on\" are" \
        -t $"implied." \

}

# ------------------------------------------------------------------------------
# Finally call the library to execute the script
# ------------------------------------------------------------------------------
main "$@" ; quit

# the end
